### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by KitsuneUdon** [Vista-Ultimate/NC_112#1]
We've got a few options of final hosting, but I strong advise using Digital Ocean's $5/mo plan. Fully functional linux server with ssh access. Using github/git's `git pull` and `git push` commands, we can easily update the code on the website in less than a minute.

**Comment by Vista-Ultimate** [comment]
Here are the specs of the $5 plan I think this will work out fine for our uses
512MBMemory
1 CoreProcessor
20GBSSD Disk
1TBTransfer

**Comment by Vista-Ultimate** [comment]
Here is the specs of the $5 plan

512MBMemory
1 CoreProcessor
20GBSSD Disk
1TBTransfer
